version: '3.6'
services:
  service_template_build:
    image: builder
    build:
      context: .
      target: builder
      args:
      - GIT_USER=${GIT_USER:-engbot}
      - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
      - SERVICE_NAME=service_template
    ports:
      - 8080:8080
    environment:
      GO_ENV: ci
      GIN_MODE: test
    command: ./service_template

  service_template:
    build:
      context: .
      args:
        - GIT_USER=${GIT_USER:-engbot}
        - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
        - SERVICE_NAME=service_template
    image: service_template
    ports:
      - 8080:8080

  wait:
    image: deliveroo/circleci:0.2.8
